### PR TITLE
add support for flatpak version

### LINKED ISSUE #79: Can't install in firefox flatpak version
Says... `Check Firefox installation ... failed, please check Firefox installation, unable to find /home/user/.mozilla/firefox` as I've installed firefox from flatpak.

### PR DESCRIPTION
**Pull request by Surendrajat**
closes #79

### CODE REVIEW

**Comment by Surendrajat** [comment]
@Zonnev Guess edc1816b985 needs to be reverted after this?

**Comment by Zonnev** [comment]
Hi @Surendrajat 

Your adjustments to the installer didn't work for me. 
1. installer stops when failing to see the Firefox directory of the repo version.
2. installer doesn't create a chrome folder in the directory of the flatpak version and never puts the userChrome in it.

Can you look at these issues? Thank you for your efforts!

**Comment by Surendrajat** [comment]
@Zonnev, of course, it won't. Only the default theme will work because other files are being fetched from other repo. 
See:
`curl -s -o- https://raw.githubusercontent.com/DRHAX34/elementaryos-firefox-theme/master/Windows/install.sh | bash
`

Someone messed up this or it was never updated :) I can open another PR for it if you want.

**Comment by Zonnev** [comment]
I wish no matter what button layout I choose, installer should install the chosen layout in the repo or the flatpak version or both directories, whatever the installer finds on the system.

You can open another PR for it, I just hope what I wish is possible to make. Good luck @Surendrajat :)

**Comment by Surendrajat** [comment]
It's done. Check #81

**Pull request merged**
