### PR TITLE
Improved install script and individual scripts for each folder

### PR DESCRIPTION
**Pull request by DRHAX34**
Hi! It's DrHax34 from Reddit! I have tested the main script (and all of the other scripts) and it's working beautifully. Please review this and get back to me if you find any issue.

Thanks!

### CODE REVIEW

**Comment by Zonnev** [comment]
Hi, great work so far but can you make the script stop at the selections? So far it installs default immediately.

**Comment by DRHAX34** [comment]
Hi, weird, it wasn't happening to me. I'll fix it right away.

**Comment by DRHAX34** [comment]
Are you using some other terminal? Besides bash? It stops for me since I'm
calling "read".

**Comment by Zonnev** [comment]
I'm using the terminal in eOS.

**Comment by Zonnev** [comment]
I have to press enter when copying and pasting the one line installer.

**Comment by DRHAX34** [comment]
I don't get it, it's supposed to stop there, I just cloned your repository
and it's stopping at the selections... Can you share a video of it
happening?

**Comment by DRHAX34** [comment]
I'm gonna quickly install a stock elementaryos vm and check.

**Comment by Zonnev** [comment]
Thanks, cause I dont have a screen recorder.

**Comment by Zonnev** [comment]
[Screencast van 2020-04-20 22.10.06.webm.zip](https://github.com/Zonnev/elementaryos-firefox-theme/files/4505921/Screencast.van.2020-04-20.22.10.06.webm.zip)
Zipped a video of it.

**Comment by DRHAX34** [comment]
Just saw it, thanks a bunch!

Derp by me, I wasn't running it like specified in the readme. Should be 
fixed now!

(Sent by Email app in ElementaryOS)
Em seg, 20 de abr de 2020 às 21:13, Zonnev <notifications@github.com> 
escreveu:

**Pull request merged**
