### PR TITLE
feat: theme installation for TorBrowser support

### PR DESCRIPTION
**Pull request by sempasha**
In favor of issue #170, now theme installation is supported for:

1. 🧅 Tor Browser;
2. 🧅 Tor Browser (📦 Flatpak).

### CODE REVIEW

**Comment by Zonnev** [comment]
Hello, I installed Tor Browser flatpak from the link in `readme`, but the installer doesn't look for the Tor Browser in `.var`. In the installer Tor Browser doesn't get mentioned as if the installer doesn't know Tor Broswer Flatpak is installed. Can you look at what's wrong? Thank you!

**Comment by sempasha** [comment]
Did you tried to run Tor Browser after installation Tor Browser Launcher installation? As I know profile directory appears right after first time browser started.

**Comment by Zonnev** [comment]
Maybe it because I have a dutch version of Tor Browser? The profile folder is in a folder with ` _nl ` behind the name: `.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_nl/Browser/TorBrowser/Data/Browser/profile.default`

**Comment by sempasha** [comment]
You said, your Tor Browser installation has nl (Dutch) locale (I saw message several minutes ago, now message has desapeared, may be it is deleted). If it is true, this may be the reason of installation script wrong behavior. Script is guessing user locale during installation, my locale is en-US and I have not tested this point well.

**Comment by Zonnev** [comment]
Sorry I deleted my reply because I saw in your script you had the locale specified so I thought my reply was useless ;) I will try locale like yours.

**Comment by Zonnev** [comment]
Same thing happens with en_US locale: still no detection of Tor Browser in the installer script. I installed Tor Browser and after it I run it, even let it connect, it makes a `profile.default` directory but the installer script doesn't see it... Am I doing something wrong?

`.var/app/com.github.micahflee.torbrowser-launcher/data/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser`

**Comment by sempasha** [comment]
I think install.sh doing something wrong, not you 😉 . Could you please share result of command below?
```bash
echo ${LANG} | cut -d '.' -f 1 | tr '_' '-'
```

**Comment by Zonnev** [comment]
`nl-NL`

**Comment by sempasha** [comment]
When install.sh explores profiles of Tor Browser (no matter flatpak version or not) it is looking for profiles at directory with path segment `tor-browser_${LOCALE}`, in my case it is `tor-browser_en-US`, in your case it is `tor-browser_nl`. I made a wrong decision to use `${LOCALE}` variable which is result of `echo ${LANG} | cut -d '.' -f 1 | tr '_' '-'` expression, because in my case locale name `en-US` matches with directory name part `en-US`. Otherwise in your case locale `nl-NL` does not match with part of directory name `nl`. And of course I didn't know about you can force installation of `en-US` Tor Browser version while your locale is not `en-US`. I'll try to use wildcard `*` for Tor Browser profiles discovery instead of LOCALE.

**Pull request merged**
